# Generated by Copilot and not cleaned

import numpy as np
import pytest

from MTH2210.EDO.rk4 import rk4


# ============================================================
# ✅ 1. Simple scalar test (dx/dt = 1 → x = t)
# ============================================================
def test_rk4_linear_solution():
    f = lambda x, t: 1.0
    x0 = 0.0
    t0, tm = 0.0, 1.0
    m = 10

    list_x, list_t = rk4(f, x0, t0, tm, m)

    # Exact solution: x(t) = t
    assert np.allclose(list_x, list_t, atol=1e-10)


# ============================================================
# ✅ 2. Exponential growth (dx/dt = x)
# ============================================================
def test_rk4_exponential():
    f = lambda x, t: x
    x0 = 1.0
    t0, tm = 0.0, 1.0
    m = 100

    list_x, list_t = rk4(f, x0, t0, tm, m)

    expected = np.exp(list_t)

    assert np.allclose(list_x, expected, atol=1e-3)


# ============================================================
# ✅ 3. Vector-valued system
# ============================================================
def test_rk4_vector_case():
    f = lambda x, t: np.array([x[1], -x[0]])  # rotation system
    x0 = np.array([1.0, 0.0])
    t0, tm = 0.0, np.pi / 2
    m = 200

    list_x, list_t = rk4(f, x0, t0, tm, m)

    final_x = list_x[-1]

    # Expected solution at pi/2: (0, -1)
    expected = np.array([0.0, -1.0])

    assert np.allclose(final_x, expected, atol=1e-2)


# ============================================================
# ✅ 4. Output size consistency
# ============================================================
def test_rk4_output_length():
    f = lambda x, t: x
    x0 = 1.0
    t0, tm = 0.0, 2.0
    m = 50

    list_x, list_t = rk4(f, x0, t0, tm, m)

    assert len(list_x) == m + 1
    assert len(list_t) == m + 1


# ============================================================
# ✅ 5. Constant solution
# ============================================================
def test_rk4_constant_solution():
    f = lambda x, t: 0.0
    x0 = 5.0

    list_x, _ = rk4(f, x0, 0.0, 10.0, 20)

    assert np.allclose(list_x, x0)


# ============================================================
# ✅ 6. Error on invalid function
# ============================================================
def test_rk4_invalid_function():
    def f(x, t):
        return "invalid"  # wrong type

    with pytest.raises(Exception):
        rk4(f, 1.0, 0.0, 1.0, 10)


# ============================================================
# ✅ 7. Negative steps should fail
# ============================================================
def test_rk4_negative_steps():
    f = lambda x, t: x

    with pytest.raises(ValueError):
        rk4(f, 1.0, 0.0, 1.0, -5)
